# Snowcover analysis on cloudfree GeoTiffs (generated by cloud_eliminator.R)
# latest script version: 2012-04-04

library(rgdal)
library(raster)

# change settings here --------------------------------------------------
setwd('C:/AHT.PRO/Pakistan_Modelling/Data/Snowcover/MODIS/TIFs/') # set working directory = location of TIF files
SRM_zones <- "catchmnt0.tif" # new ez classification with 500m steps, total mangla catchment
tifpat <- "...._.._...tif"
outf <- "snowcover_0.txt"
nez <- 11 # number of elevation zones
# please adjust the following numbers for each run
minf <- 4200 # first file to read
maxf <- 4400 # last file to be read
# end of code section with editable settings ----------------------------

cat("Snowcover analysis - start routine:", format(Sys.time(),"%X"), "\n")
e <- raster(SRM_zones)
glistf <- list.files(pattern=tifpat) # load complete file list of cloudfree TIFs into a R character vector
v <-c(25, 200) # non-snow, snow -- only 2 classes left after removal of clouds and "undecided" cells
maxf <- max(maxf, length(glistf))

for (i in minf:maxf){
  if (is.na(glistf[i]) break
  day <- paste(substr(glistf[i],1,10)) 
  s <- raster (glistf[i])
  for (ez in 1:nez){
    # make new vector
    dlist <- c(day, ez, 0, 0)
    for (rc in 1:2){
      #  raster calculation
      c <- (e==ez) * (s==v[rc]) # calculates raster and stores it in memory only
      # get statistics
      dlist[2+rc]<-count(c,1) # put number of cells with value=1 into vector
    } # end loop of 2 reflection classes
    
    write(dlist, file = outf, ncolumns=4, append = TRUE,  sep = " ") # write vector contents to disk
  } # end loop of nez elevation zones
} # end of loop for daily TIFs

cat("end routine:", format(Sys.time(),"%X"), "\n")
